FROM python:3.12-slim

WORKDIR /app

COPY services/worker-python/requirements.txt /app/services/worker-python/requirements.txt
RUN pip install --no-cache-dir -r /app/services/worker-python/requirements.txt

COPY services/worker-python /app/services/worker-python
COPY sample-data /app/sample-data

ENTRYPOINT ["python", "services/worker-python/service/main.py"]
